/**
 * Author:  Алексей
 * Created: 10 янв. 2020 г.
 */
SELECT * FROM APP.PRODUCT_CODE WHERE DISCOUNT_CODE = 'N'
/*
INSERT INTO PRODUCT_CODE (PROD_CODE, DISCOUNT_CODE, DESCRIPTION) VALUES (?,?,?);
UPDATE PRODUCT_CODE SET DISCOUNT_CODE = ?, DESCRIPTION = ? WHERE PROD_CODE = ?;
*/